export const stations: { [key: string]: { [key: string]: string[] } } = {
	'Abbey Wood': { '910GABWDXR': ['elizabeth'], '910GABWD': ['thameslink'] },
	'Acton Main Line': { '910GACTONML': ['elizabeth'] },
	Burnham: { '910GBNHAM': ['elizabeth'] },
	'Bond Street': {
		'910GBONDST': ['elizabeth'],
		'940GZZLUBND': ['jubilee', 'central']
	},
	Brentwood: { '910GBRTWOOD': ['elizabeth'] },
	'Canary Wharf': {
		'910GCANWHRF': ['elizabeth'],
		'940GZZDLCAN': ['dlr'],
		'940GZZLUCYF': ['jubilee']
	},
	'Chadwell Heath': { '910GCHDWLHT': ['elizabeth'] },
	'Custom House': { '910GCSTMHSXR': ['elizabeth'], '940GZZDLCUS': ['dlr'] },
	'Ealing Broadway': {
		'910GEALINGB': ['elizabeth'],
		'940GZZLUEBY': ['district', 'central']
	},
	Farringdon: {
		'910GFRNDXR': ['elizabeth'],
		'940GZZLUFCN': ['circle', 'metropolitan', 'hammersmith-city'],
		'910GFRNDNLT': ['thameslink']
	},
	'Forest Gate': { '910GFRSTGT': ['elizabeth'] },
	'Gidea Park': { '910GGIDEAPK': ['elizabeth'] },
	Goodmayes: { '910GGODMAYS': ['elizabeth'] },
	Hanwell: { '910GHANWELL': ['elizabeth'] },
	'Hayes & Harlington': { '910GHAYESAH': ['elizabeth'] },
	'Harold Wood': { '910GHRLDWOD': ['elizabeth'] },
	'Heathrow Terminals 2 & 3': {
		'910GHTRWAPT': ['elizabeth'],
		'940GZZLUHRC': ['piccadilly']
	},
	'Heathrow Terminal 4': {
		'910GHTRWTM4': ['elizabeth'],
		'940GZZLUHR4': ['piccadilly']
	},
	'Heathrow Terminal 5': {
		'910GHTRWTM5': ['elizabeth'],
		'940GZZLUHR5': ['piccadilly']
	},
	Ilford: { '910GILFORD': ['elizabeth'] },
	Iver: { '910GIVER': ['elizabeth'] },
	Langley: { '910GLANGLEY': ['elizabeth'] },
	'Liverpool Street': {
		'910GLIVST': ['elizabeth', 'weaver'],
		'910GLIVSTLL': ['elizabeth'],
		'940GZZLULVT': ['circle', 'metropolitan', 'hammersmith-city', 'central']
	},
	'Manor Park': { '910GMANRPK': ['elizabeth'] },
	Maidenhead: { '910GMDNHEAD': ['elizabeth'] },
	Maryland: { '910GMRYLAND': ['elizabeth'] },
	Paddington: {
		'910GPADTLL': ['elizabeth'],
		'910GPADTON': ['elizabeth'],
		'940GZZLUPAC': ['district', 'circle', 'bakerloo']
	},
	Reading: { '910GRDNGSTN': ['elizabeth'] },
	Romford: { '910GROMFORD': ['elizabeth', 'liberty'] },
	Shenfield: { '910GSHENFLD': ['elizabeth'] },
	Slough: { '910GSLOUGH': ['elizabeth'] },
	Stratford: {
		'910GSTFD': ['elizabeth', 'mildmay'],
		'940GZZDLSTD': ['dlr'],
		'940GZZLUSTD': ['jubilee', 'central']
	},
	Southall: { '910GSTHALL': ['elizabeth'] },
	'Seven Kings': { '910GSVNKNGS': ['elizabeth'] },
	Taplow: { '910GTAPLOW': ['elizabeth'] },
	'Tottenham Court Road': {
		'910GTOTCTRD': ['elizabeth'],
		'940GZZLUTCR': ['central', 'northern']
	},
	Twyford: { '910GTWYFORD': ['elizabeth'] },
	Whitechapel: {
		'910GWCHAPXR': ['elizabeth'],
		'940GZZLUWPL': ['district', 'hammersmith-city'],
		'910GWCHAPEL': ['windrush']
	},
	'West Drayton': { '910GWDRYTON': ['elizabeth'] },
	'West Ealing': { '910GWEALING': ['elizabeth'] },
	Woolwich: { '910GWOLWXR': ['elizabeth'] },
	'Abbey Road': { '940GZZDLABR': ['dlr'] },
	'All Saints': { '940GZZDLALL': ['dlr'] },
	Beckton: { '940GZZDLBEC': ['dlr'] },
	Blackwall: { '940GZZDLBLA': ['dlr'] },
	Bank: {
		'940GZZDLBNK': ['dlr'],
		'940GZZLUBNK': ['waterloo-city', 'central', 'northern']
	},
	'Bow Church': { '940GZZDLBOW': ['dlr'] },
	'Beckton Park': { '940GZZDLBPK': ['dlr'] },
	'Canning Town': { '940GZZDLCGT': ['dlr'], '940GZZLUCGT': ['jubilee'] },
	Crossharbour: { '940GZZDLCLA': ['dlr'] },
	'Cutty Sark': { '940GZZDLCUT': ['dlr'] },
	Cyprus: { '940GZZDLCYP': ['dlr'] },
	'Deptford Bridge': { '940GZZDLDEP': ['dlr'] },
	'Devons Road': { '940GZZDLDEV': ['dlr'] },
	'East India': { '940GZZDLEIN': ['dlr'] },
	'Elverson Road': { '940GZZDLELV': ['dlr'] },
	'Gallions Reach': { '940GZZDLGAL': ['dlr'] },
	Greenwich: { '940GZZDLGRE': ['dlr'], '910GGNWH': ['thameslink'] },
	'Heron Quays': { '940GZZDLHEQ': ['dlr'] },
	'Island Gardens': { '940GZZDLISL': ['dlr'] },
	'King George V': { '940GZZDLKGV': ['dlr'] },
	'London City Airport': { '940GZZDLLCA': ['dlr'] },
	'Langdon Park': { '940GZZDLLDP': ['dlr'] },
	Lewisham: { '940GZZDLLEW': ['dlr'], '910GLEWISHM': ['thameslink'] },
	Limehouse: { '940GZZDLLIM': ['dlr'] },
	Mudchute: { '940GZZDLMUD': ['dlr'] },
	'Pontoon Dock': { '940GZZDLPDK': ['dlr'] },
	Poplar: { '940GZZDLPOP': ['dlr'] },
	'Prince Regent': { '940GZZDLPRE': ['dlr'] },
	'Pudding Mill Lane': { '940GZZDLPUD': ['dlr'] },
	'Royal Albert': { '940GZZDLRAL': ['dlr'] },
	'Royal Victoria': { '940GZZDLRVC': ['dlr'] },
	Shadwell: { '940GZZDLSHA': ['dlr'], '910GSHADWEL': ['windrush'] },
	'Stratford High Street': { '940GZZDLSHS': ['dlr'] },
	'Stratford International': { '940GZZDLSIT': ['dlr'] },
	'South Quay': { '940GZZDLSOQ': ['dlr'] },
	'Star Lane': { '940GZZDLSTL': ['dlr'] },
	'Tower Gateway': { '940GZZDLTWG': ['dlr'] },
	Westferry: { '940GZZDLWFE': ['dlr'] },
	'West Ham': {
		'940GZZDLWHM': ['dlr'],
		'940GZZLUWHM': ['district', 'hammersmith-city', 'jubilee']
	},
	'West India Quay': { '940GZZDLWIQ': ['dlr'] },
	'Woolwich Arsenal': { '940GZZDLWLA': ['dlr'], '910GWOLWCHA': ['thameslink'] },
	'West Silvertown': { '940GZZDLWSV': ['dlr'] },
	'Baker Street': {
		'940GZZLUBST': ['hammersmith-city', 'circle', 'jubilee', 'metropolitan', 'bakerloo']
	},
	'Charing Cross': { '940GZZLUCHX': ['bakerloo', 'northern'] },
	'Elephant & Castle': {
		'940GZZLUEAC': ['bakerloo', 'northern'],
		'910GELPHNAC': ['thameslink']
	},
	Embankment: {
		'940GZZLUEMB': ['district', 'circle', 'bakerloo', 'northern']
	},
	'Edgware Road': {
		'940GZZLUERB': ['bakerloo'],
		'940GZZLUERC': ['district', 'circle', 'hammersmith-city']
	},
	'Harrow & Wealdstone': {
		'940GZZLUHAW': ['bakerloo'],
		'910GHROW': ['lioness']
	},
	Harlesden: { '940GZZLUHSN': ['bakerloo'], '910GHARLSDN': ['lioness'] },
	Kenton: { '940GZZLUKEN': ['bakerloo'], '910GKTON': ['lioness'] },
	'Kilburn Park': { '940GZZLUKPK': ['bakerloo'] },
	'Kensal Green': { '940GZZLUKSL': ['bakerloo'], '910GKENSLG': ['lioness'] },
	'Lambeth North': { '940GZZLULBN': ['bakerloo'] },
	'Maida Vale': { '940GZZLUMVL': ['bakerloo'] },
	Marylebone: { '940GZZLUMYB': ['bakerloo'] },
	'North Wembley': { '940GZZLUNWY': ['bakerloo'], '910GNWEMBLY': ['lioness'] },
	'Oxford Circus': { '940GZZLUOXC': ['bakerloo', 'victoria', 'central'] },
	'Piccadilly Circus': { '940GZZLUPCC': ['piccadilly', 'bakerloo'] },
	"Queen's Park": { '940GZZLUQPS': ['bakerloo'] },
	"Regent's Park": { '940GZZLURGP': ['bakerloo'] },
	'Stonebridge Park': {
		'940GZZLUSGP': ['bakerloo'],
		'910GSTNBGPK': ['lioness']
	},
	'South Kenton': { '940GZZLUSKT': ['bakerloo'], '910GSKENTON': ['lioness'] },
	'Willesden Junction': {
		'940GZZLUWJN': ['bakerloo'],
		'910GWLSDJHL': ['mildmay', 'lioness']
	},
	'Warwick Avenue': { '940GZZLUWKA': ['bakerloo'] },
	Waterloo: {
		'940GZZLUWLO': ['waterloo-city', 'bakerloo', 'jubilee', 'northern']
	},
	'Wembley Central': { '940GZZLUWYC': ['bakerloo'], '910GWMBY': ['lioness'] },
	Barkingside: { '940GZZLUBKE': ['central'] },
	'Buckhurst Hill': { '940GZZLUBKH': ['central'] },
	'Bethnal Green': { '940GZZLUBLG': ['central'], '910GBTHNLGR': ['weaver'] },
	'Chancery Lane': { '940GZZLUCHL': ['central'] },
	Chigwell: { '940GZZLUCWL': ['central'] },
	Debden: { '940GZZLUDBN': ['central'] },
	'East Acton': { '940GZZLUEAN': ['central'] },
	Epping: { '940GZZLUEPG': ['central'] },
	Fairlop: { '940GZZLUFLP': ['central'] },
	Greenford: { '940GZZLUGFD': ['central'] },
	'Grange Hill': { '940GZZLUGGH': ['central'] },
	'Gants Hill': { '940GZZLUGTH': ['central'] },
	Holborn: { '940GZZLUHBN': ['piccadilly', 'central'] },
	'Hanger Lane': { '940GZZLUHGR': ['central'] },
	Hainault: { '940GZZLUHLT': ['central'] },
	'Holland Park': { '940GZZLUHPK': ['central'] },
	Loughton: { '940GZZLULGN': ['central'] },
	'Lancaster Gate': { '940GZZLULGT': ['central'] },
	Leyton: { '940GZZLULYN': ['central'] },
	Leytonstone: { '940GZZLULYS': ['central'] },
	'Marble Arch': { '940GZZLUMBA': ['central'] },
	'Mile End': { '940GZZLUMED': ['district', 'hammersmith-city', 'central'] },
	'North Acton': { '940GZZLUNAN': ['central'] },
	'Newbury Park': { '940GZZLUNBP': ['central'] },
	'Notting Hill Gate': { '940GZZLUNHG': ['district', 'circle', 'central'] },
	Northolt: { '940GZZLUNHT': ['central'] },
	Perivale: { '940GZZLUPVL': ['central'] },
	Queensway: { '940GZZLUQWY': ['central'] },
	Redbridge: { '940GZZLURBG': ['central'] },
	'Ruislip Gardens': { '940GZZLURSG': ['central'] },
	'Roding Valley': { '940GZZLURVY': ['central'] },
	"Shepherd's Bush": { '940GZZLUSBC': ['central'] },
	Snaresbrook: { '940GZZLUSNB': ['central'] },
	"St. Paul's": { '940GZZLUSPU': ['central'] },
	'South Ruislip': { '940GZZLUSRP': ['central'] },
	'South Woodford': { '940GZZLUSWF': ['central'] },
	'Theydon Bois': { '940GZZLUTHB': ['central'] },
	'White City': { '940GZZLUWCY': ['central'] },
	Woodford: { '940GZZLUWOF': ['central'] },
	'West Ruislip': { '940GZZLUWRP': ['central'] },
	Wanstead: { '940GZZLUWSD': ['central'] },
	'West Acton': { '940GZZLUWTA': ['central'] },
	Aldgate: { '940GZZLUALD': ['circle', 'metropolitan'] },
	Barbican: { '940GZZLUBBN': ['circle', 'metropolitan', 'hammersmith-city'] },
	Blackfriars: {
		'940GZZLUBKF': ['district', 'circle'],
		'910GBLFR': ['thameslink']
	},
	Bayswater: { '940GZZLUBWT': ['district', 'circle'] },
	'Cannon Street': { '940GZZLUCST': ['district', 'circle'] },
	'Euston Square': {
		'940GZZLUESQ': ['circle', 'metropolitan', 'hammersmith-city']
	},
	'Goldhawk Road': { '940GZZLUGHK': ['circle', 'hammersmith-city'] },
	'Great Portland Street': {
		'940GZZLUGPS': ['circle', 'metropolitan', 'hammersmith-city']
	},
	'Gloucester Road': { '940GZZLUGTR': ['district', 'circle', 'piccadilly'] },
	Hammersmith: {
		'940GZZLUHSC': ['circle', 'hammersmith-city'],
		'940GZZLUHSD': ['district', 'piccadilly']
	},
	'High Street Kensington': { '940GZZLUHSK': ['district', 'circle'] },
	"King's Cross St. Pancras": {
		'940GZZLUKSX': [
			'hammersmith-city',
			'northern',
			'circle',
			'metropolitan',
			'piccadilly',
			'victoria'
		]
	},
	'Ladbroke Grove': { '940GZZLULAD': ['circle', 'hammersmith-city'] },
	'Latimer Road': { '940GZZLULRD': ['circle', 'hammersmith-city'] },
	Moorgate: {
		'940GZZLUMGT': ['circle', 'metropolitan', 'hammersmith-city', 'northern']
	},
	Monument: { '940GZZLUMMT': ['district', 'circle'] },
	'Mansion House': { '940GZZLUMSH': ['district', 'circle'] },
	'Paddington -': { '940GZZLUPAH': ['circle', 'hammersmith-city'] },
	'Royal Oak': { '940GZZLURYO': ['circle', 'hammersmith-city'] },
	"Shepherd's Bush Market": { '940GZZLUSBM': ['circle', 'hammersmith-city'] },
	"St. James's Park": { '940GZZLUSJP': ['district', 'circle'] },
	'South Kensington': { '940GZZLUSKS': ['district', 'circle', 'piccadilly'] },
	'Sloane Square': { '940GZZLUSSQ': ['district', 'circle'] },
	Temple: { '940GZZLUTMP': ['district', 'circle'] },
	'Tower Hill': { '940GZZLUTWH': ['district', 'circle'] },
	Victoria: {
		'940GZZLUVIC': ['district', 'circle', 'victoria'],
		'910GVICTRIC': ['thameslink']
	},
	'Wood Lane': { '940GZZLUWLA': ['circle', 'hammersmith-city'] },
	Westminster: { '940GZZLUWSM': ['district', 'circle', 'jubilee'] },
	'Westbourne Park': { '940GZZLUWSP': ['circle', 'hammersmith-city'] },
	'Acton Town': { '940GZZLUACT': ['district', 'piccadilly'] },
	'Aldgate East': { '940GZZLUADE': ['district', 'hammersmith-city'] },
	'Bromley-by-Bow': { '940GZZLUBBB': ['district', 'hammersmith-city'] },
	Becontree: { '940GZZLUBEC': ['district'] },
	Barking: {
		'940GZZLUBKG': ['district', 'hammersmith-city'],
		'910GBARKING': ['suffragette']
	},
	'Barons Court': { '940GZZLUBSC': ['district', 'piccadilly'] },
	'Bow Road': { '940GZZLUBWR': ['district', 'hammersmith-city'] },
	'Chiswick Park': { '940GZZLUCWP': ['district'] },
	'Dagenham East': { '940GZZLUDGE': ['district'] },
	'Dagenham Heathway': { '940GZZLUDGY': ['district'] },
	'Ealing Common': { '940GZZLUECM': ['district', 'piccadilly'] },
	"Earl's Court": { '940GZZLUECT': ['district', 'piccadilly'] },
	'East Ham': { '940GZZLUEHM': ['district', 'hammersmith-city'] },
	'Elm Park': { '940GZZLUEPK': ['district'] },
	'East Putney': { '940GZZLUEPY': ['district'] },
	'Fulham Broadway': { '940GZZLUFBY': ['district'] },
	Gunnersbury: { '940GZZLUGBY': ['district'], '910GGNRSBRY': ['mildmay'] },
	Hornchurch: { '940GZZLUHCH': ['district'] },
	Kensington: { '940GZZLUKOY': ['district'], '910GKENOLYM': ['mildmay'] },
	'Kew Gardens': { '940GZZLUKWG': ['district'], '910GKEWGRDN': ['mildmay'] },
	Plaistow: { '940GZZLUPLW': ['district', 'hammersmith-city'] },
	'Parsons Green': { '940GZZLUPSG': ['district'] },
	'Putney Bridge': { '940GZZLUPYB': ['district'] },
	Richmond: { '940GZZLURMD': ['district'], '910GRICHMND': ['mildmay'] },
	'Ravenscourt Park': { '940GZZLURVP': ['district'] },
	'Stamford Brook': { '940GZZLUSFB': ['district'] },
	Southfields: { '940GZZLUSFS': ['district'] },
	'Stepney Green': { '940GZZLUSGN': ['district', 'hammersmith-city'] },
	'Turnham Green': { '940GZZLUTNG': ['district', 'piccadilly'] },
	'Upminster Bridge': { '940GZZLUUPB': ['district'] },
	'Upton Park': { '940GZZLUUPK': ['district', 'hammersmith-city'] },
	Upminster: { '940GZZLUUPM': ['district'], '910GUPMNSTR': ['liberty'] },
	Upney: { '940GZZLUUPY': ['district'] },
	'West Brompton': { '940GZZLUWBN': ['district'], '910GWBRMPTN': ['mildmay'] },
	Wimbledon: {
		'940GZZLUWIM': ['district'],
		'910GWIMBLDN': ['thameslink'],
		'9400ZZCRWMB1': ['tram'],
		'940GZZCRWMB': ['tram']
	},
	'Wimbledon Park': { '940GZZLUWIP': ['district'] },
	'West Kensington': { '940GZZLUWKN': ['district'] },
	Bermondsey: { '940GZZLUBMY': ['jubilee'] },
	'Canons Park': { '940GZZLUCPK': ['jubilee'] },
	'Canada Water': { '940GZZLUCWR': ['jubilee'], '910GCNDAW': ['windrush'] },
	'Dollis Hill': { '940GZZLUDOH': ['jubilee'] },
	'Finchley Road': { '940GZZLUFYR': ['metropolitan', 'jubilee'] },
	'Green Park': { '940GZZLUGPK': ['piccadilly', 'jubilee', 'victoria'] },
	Kilburn: { '940GZZLUKBN': ['jubilee'] },
	Kingsbury: { '940GZZLUKBY': ['jubilee'] },
	'London Bridge': {
		'940GZZLULNB': ['jubilee', 'northern'],
		'910GLNDNBDC': ['thameslink']
	},
	Neasden: { '940GZZLUNDN': ['jubilee'] },
	'North Greenwich': { '940GZZLUNGW': ['jubilee'] },
	Queensbury: { '940GZZLUQBY': ['jubilee'] },
	"St. John's Wood": { '940GZZLUSJW': ['jubilee'] },
	Stanmore: { '940GZZLUSTM': ['jubilee'] },
	'Swiss Cottage': { '940GZZLUSWC': ['jubilee'] },
	Southwark: { '940GZZLUSWK': ['jubilee'] },
	'West Hampstead': { '940GZZLUWHP': ['jubilee'], '910GWHMDSTD': ['mildmay'] },
	'Willesden Green': { '940GZZLUWIG': ['metropolitan', 'jubilee'] },
	'Wembley Park': { '940GZZLUWYP': ['metropolitan', 'jubilee'] },
	Amersham: { '940GZZLUAMS': ['metropolitan'] },
	'Chalfont & Latimer': { '940GZZLUCAL': ['metropolitan'] },
	Chesham: { '940GZZLUCSM': ['metropolitan'] },
	Croxley: { '940GZZLUCXY': ['metropolitan'] },
	Chorleywood: { '940GZZLUCYD': ['metropolitan'] },
	Eastcote: { '940GZZLUEAE': ['piccadilly', 'metropolitan'] },
	Hillingdon: { '940GZZLUHGD': ['piccadilly', 'metropolitan'] },
	'Harrow-on-the-Hill': { '940GZZLUHOH': ['metropolitan'] },
	Ickenham: { '940GZZLUICK': ['piccadilly', 'metropolitan'] },
	'Moor Park': { '940GZZLUMPK': ['metropolitan'] },
	'North Harrow': { '940GZZLUNHA': ['metropolitan'] },
	'Northwick Park': { '940GZZLUNKP': ['metropolitan'] },
	Northwood: { '940GZZLUNOW': ['metropolitan'] },
	'Northwood Hills': { '940GZZLUNWH': ['metropolitan'] },
	Pinner: { '940GZZLUPNR': ['metropolitan'] },
	'Preston Road': { '940GZZLUPRD': ['metropolitan'] },
	Rickmansworth: { '940GZZLURKW': ['metropolitan'] },
	'Ruislip Manor': { '940GZZLURSM': ['piccadilly', 'metropolitan'] },
	Ruislip: { '940GZZLURSP': ['piccadilly', 'metropolitan'] },
	'Rayners Lane': { '940GZZLURYL': ['piccadilly', 'metropolitan'] },
	Uxbridge: { '940GZZLUUXB': ['piccadilly', 'metropolitan'] },
	Watford: { '940GZZLUWAF': ['metropolitan'] },
	'West Harrow': { '940GZZLUWHW': ['metropolitan'] },
	'Battersea Power Station': { '940GZZBPSUST': ['northern'] },
	Archway: { '940GZZLUACY': ['northern'] },
	Angel: { '940GZZLUAGL': ['northern'] },
	Balham: { '940GZZLUBLM': ['northern'] },
	Borough: { '940GZZLUBOR': ['northern'] },
	'Burnt Oak': { '940GZZLUBTK': ['northern'] },
	'Brent Cross': { '940GZZLUBTX': ['northern'] },
	'Belsize Park': { '940GZZLUBZP': ['northern'] },
	'Chalk Farm': { '940GZZLUCFM': ['northern'] },
	Colindale: { '940GZZLUCND': ['northern'] },
	'Clapham Common': { '940GZZLUCPC': ['northern'] },
	'Clapham North': { '940GZZLUCPN': ['northern'] },
	'Clapham South': { '940GZZLUCPS': ['northern'] },
	'Colliers Wood': { '940GZZLUCSD': ['northern'] },
	'Camden Town': { '940GZZLUCTN': ['northern'] },
	'East Finchley': { '940GZZLUEFY': ['northern'] },
	Edgware: { '940GZZLUEGW': ['northern'] },
	Euston: {
		'940GZZLUEUS': ['victoria', 'northern'],
		'910GEUSTON': ['lioness']
	},
	'Finchley Central': { '940GZZLUFYC': ['northern'] },
	'Goodge Street': { '940GZZLUGDG': ['northern'] },
	'Golders Green': { '940GZZLUGGN': ['northern'] },
	'High Barnet': { '940GZZLUHBT': ['northern'] },
	'Hendon Central': { '940GZZLUHCL': ['northern'] },
	Highgate: { '940GZZLUHGT': ['northern'] },
	Hampstead: { '940GZZLUHTD': ['northern'] },
	Kennington: { '940GZZLUKNG': ['northern'] },
	'Kentish Town': {
		'940GZZLUKSH': ['northern'],
		'910GKNTSHTN': ['thameslink']
	},
	'Leicester Square': { '940GZZLULSQ': ['piccadilly', 'northern'] },
	Morden: { '940GZZLUMDN': ['northern'] },
	'Mill Hill East': { '940GZZLUMHL': ['northern'] },
	'Mornington Crescent': { '940GZZLUMTC': ['northern'] },
	'Old Street': { '940GZZLUODS': ['northern'] },
	Oval: { '940GZZLUOVL': ['northern'] },
	Stockwell: { '940GZZLUSKW': ['victoria', 'northern'] },
	'South Wimbledon': { '940GZZLUSWN': ['northern'] },
	'Totteridge & Whetstone': { '940GZZLUTAW': ['northern'] },
	'Tooting Bec': { '940GZZLUTBC': ['northern'] },
	'Tooting Broadway': { '940GZZLUTBY': ['northern'] },
	'Tufnell Park': { '940GZZLUTFP': ['northern'] },
	'West Finchley': { '940GZZLUWFN': ['northern'] },
	'Woodside Park': { '940GZZLUWOP': ['northern'] },
	'Warren Street': { '940GZZLUWRR': ['victoria', 'northern'] },
	'Nine Elms': { '940GZZNEUGST': ['northern'] },
	Alperton: { '940GZZLUALP': ['piccadilly'] },
	'Arnos Grove': { '940GZZLUASG': ['piccadilly'] },
	Arsenal: { '940GZZLUASL': ['piccadilly'] },
	'Bounds Green': { '940GZZLUBDS': ['piccadilly'] },
	'Boston Manor': { '940GZZLUBOS': ['piccadilly'] },
	'Caledonian Road': { '940GZZLUCAR': ['piccadilly'] },
	'Covent Garden': { '940GZZLUCGN': ['piccadilly'] },
	Cockfosters: { '940GZZLUCKS': ['piccadilly'] },
	'Finsbury Park': {
		'940GZZLUFPK': ['piccadilly', 'victoria'],
		'910GFNPK': ['thameslink']
	},
	'Hatton Cross': { '940GZZLUHNX': ['piccadilly'] },
	'Hyde Park Corner': { '940GZZLUHPC': ['piccadilly'] },
	'Hounslow Central': { '940GZZLUHWC': ['piccadilly'] },
	'Hounslow East': { '940GZZLUHWE': ['piccadilly'] },
	'Hounslow West': { '940GZZLUHWT': ['piccadilly'] },
	'Holloway Road': { '940GZZLUHWY': ['piccadilly'] },
	Knightsbridge: { '940GZZLUKNB': ['piccadilly'] },
	'Manor House': { '940GZZLUMRH': ['piccadilly'] },
	'North Ealing': { '940GZZLUNEN': ['piccadilly'] },
	Northfields: { '940GZZLUNFD': ['piccadilly'] },
	Oakwood: { '940GZZLUOAK': ['piccadilly'] },
	Osterley: { '940GZZLUOSY': ['piccadilly'] },
	'Park Royal': { '940GZZLUPKR': ['piccadilly'] },
	'Russell Square': { '940GZZLURSQ': ['piccadilly'] },
	'South Ealing': { '940GZZLUSEA': ['piccadilly'] },
	Southgate: { '940GZZLUSGT': ['piccadilly'] },
	'South Harrow': { '940GZZLUSHH': ['piccadilly'] },
	'Sudbury Hill': { '940GZZLUSUH': ['piccadilly'] },
	'Sudbury Town': { '940GZZLUSUT': ['piccadilly'] },
	'Turnpike Lane': { '940GZZLUTPN': ['piccadilly'] },
	'Wood Green': { '940GZZLUWOG': ['piccadilly'] },
	'Blackhorse Road': {
		'940GZZLUBLR': ['victoria'],
		'910GBLCHSRD': ['suffragette']
	},
	Brixton: { '940GZZLUBXN': ['victoria'] },
	'Highbury & Islington': {
		'940GZZLUHAI': ['victoria'],
		'910GHGHI': ['mildmay', 'windrush']
	},
	Pimlico: { '940GZZLUPCO': ['victoria'] },
	'Seven Sisters': { '940GZZLUSVS': ['victoria'], '910GSEVNSIS': ['weaver'] },
	'Tottenham Hale': { '940GZZLUTMH': ['victoria'] },
	Vauxhall: { '940GZZLUVXL': ['victoria'] },
	'Walthamstow Central': {
		'940GZZLUWWL': ['victoria'],
		'910GWLTWCEN': ['weaver']
	},
	'Emerson Park': { '910GEMRSPKH': ['liberty'] },
	Bushey: { '910GBUSHYDC': ['lioness'] },
	'Carpenders Park': { '910GCRPNDPK': ['lioness'] },
	'Headstone Lane': { '910GHEDSTNL': ['lioness'] },
	'Hatch End': { '910GHTCHEND': ['lioness'] },
	'Kilburn High Road': { '910GKLBRNHR': ['lioness'] },
	'Queens Park': { '910GQPRK': ['lioness'] },
	'South Hampstead': { '910GSHMPSTD': ['lioness'] },
	'Watford High Street': { '910GWATFDHS': ['lioness'] },
	'Watford Junction': { '910GWATFJDC': ['lioness'] },
	'Acton Central': { '910GACTNCTL': ['mildmay'] },
	Brondesbury: { '910GBRBY': ['mildmay'] },
	'Brondesbury Park': { '910GBRBYPK': ['mildmay'] },
	'Caledonian Road & Barnsbury': { '910GCLDNNRB': ['mildmay'] },
	'Clapham Junction': {
		'910GCLPHMJ1': ['mildmay', 'windrush'],
		'910GCLPHMJC': ['mildmay']
	},
	'Camden Road': { '910GCMDNRD': ['mildmay'] },
	Canonbury: { '910GCNNB': ['mildmay', 'windrush'] },
	'Imperial Wharf': { '910GCSEAH': ['mildmay'] },
	'Dalston Kingsland': { '910GDALSKLD': ['mildmay'] },
	'Finchley Road & Frognal': { '910GFNCHLYR': ['mildmay'] },
	'Gospel Oak': { '910GGOSPLOK': ['mildmay', 'suffragette'] },
	'Hackney Central': { '910GHACKNYC': ['mildmay'] },
	'Hackney Wick': { '910GHACKNYW': ['mildmay'] },
	'Hampstead Heath': { '910GHMPSTDH': ['mildmay'] },
	Homerton: { '910GHOMRTON': ['mildmay'] },
	'Kensal Rise': { '910GKENR': ['mildmay'] },
	'Kentish Town West': { '910GKNTSHTW': ['mildmay'] },
	'South Acton': { '910GSACTON': ['mildmay'] },
	'Shepherds Bush': { '910GSHPDSB': ['mildmay'] },
	'Barking Riverside': { '910GBKRVS': ['suffragette'] },
	'Crouch Hill': { '910GCROUCHH': ['suffragette'] },
	'Harringay Green Lanes': { '910GHRGYGL': ['suffragette'] },
	'Leyton Midland Road': { '910GLEYTNMR': ['suffragette'] },
	'Leytonstone High Road': { '910GLYTNSHR': ['suffragette'] },
	'South Tottenham': { '910GSTOTNHM': ['suffragette'] },
	'Upper Holloway': { '910GUPRHLWY': ['suffragette'] },
	'Woodgrange Park': { '910GWDGRNPK': ['suffragette'] },
	'Walthamstow Queens Road': { '910GWLTHQRD': ['suffragette'] },
	'Wanstead Park': { '910GWNSTDPK': ['suffragette'] },
	'Bush Hill Park': { '910GBHILLPK': ['weaver'] },
	'Bruce Grove': { '910GBRUCGRV': ['weaver'] },
	'Cambridge Heath': { '910GCAMHTH': ['weaver'] },
	Cheshunt: { '910GCHESHNT': ['weaver'] },
	Chingford: { '910GCHINGFD': ['weaver'] },
	Clapton: { '910GCLAPTON': ['weaver'] },
	'Edmonton Green': { '910GEDMNGRN': ['weaver'] },
	'Enfield Town': { '910GENFLDTN': ['weaver'] },
	'Hackney Downs': { '910GHAKNYNM': ['weaver'] },
	'Highams Park': { '910GHGHMSPK': ['weaver'] },
	Fields: { '910GLONFLDS': ['weaver'] },
	'Rectory Road': { '910GRCTRYRD': ['weaver'] },
	Southbury: { '910GSBURY': ['weaver'] },
	'Silver Street': { '910GSIVRST': ['weaver'] },
	'St James Street': { '910GSTJMSST': ['weaver'] },
	'Stoke Newington': { '910GSTKNWNG': ['weaver'] },
	'Stamford Hill': { '910GSTMFDHL': ['weaver'] },
	'Theobalds Grove': { '910GTHBLDSG': ['weaver'] },
	'Turkey Street': { '910GTURKYST': ['weaver'] },
	'Wood Street': { '910GWDST': ['weaver'] },
	'White Hart Lane': { '910GWHHRTLA': ['weaver'] },
	Anerley: { '910GANERLEY': ['windrush'] },
	Brockley: { '910GBROCKLY': ['windrush'] },
	'Clapham High Street': { '910GCLPHHS': ['windrush'] },
	'Crystal Palace': { '910GCRYSTLP': ['windrush'] },
	'Dalston Junction': { '910GDALS': ['windrush'] },
	'Denmark Hill': { '910GDENMRKH': ['thameslink', 'windrush'] },
	'Forest Hill': { '910GFORESTH': ['windrush'] },
	Haggerston: { '910GHAGGERS': ['windrush'] },
	'Honor Oak Park': { '910GHONROPK': ['windrush'] },
	Hoxton: { '910GHOXTON': ['windrush'] },
	'New Cross Gate': { '910GNEWXGTE': ['windrush'] },
	'Norwood Junction': { '910GNORWDJ': ['thameslink', 'windrush'] },
	'New Cross ELL': { '910GNWCRELL': ['windrush'] },
	'Queens Road Peckham': { '910GPCKHMQD': ['windrush'] },
	'Peckham Rye': { '910GPCKHMRY': ['thameslink', 'windrush'] },
	'Penge West': { '910GPENEW': ['windrush'] },
	Rotherhithe: { '910GRTHERHI': ['windrush'] },
	'Shoreditch High Street': { '910GSHRDHST': ['windrush'] },
	'Surrey Quays': { '910GSURREYQ': ['windrush'] },
	Sydenham: { '910GSYDENHM': ['windrush'] },
	Wapping: { '910GWAPPING': ['windrush'] },
	'West Croydon': {
		'910GWCROYDN': ['windrush'],
		'9400ZZCRWCR1': ['tram'],
		'940GZZCRWCR': ['tram']
	},
	'Wandsworth Road': { '910GWNDSWRD': ['windrush'] },
	'Alexandra Palace': { '910GALEXNDP': ['thameslink'] },
	Arlesey: { '910GARLSEY': ['thameslink'] },
	'Ashwell & Morden': { '910GASHWELC': ['thameslink'] },
	Balcombe: { '910GBALCOMB': ['thameslink'] },
	Baldock: { '910GBALDOCK': ['thameslink'] },
	'Bat & Ball': { '910GBATABAL': ['thameslink'] },
	'Beckenham Hill': { '910GBCKNHMH': ['thameslink'] },
	'Beckenham Junction': {
		'910GBCKNHMJ': ['thameslink'],
		'9400ZZCRBEK1': ['tram'],
		'940GZZCRBEK': ['tram']
	},
	Bedford: { '910GBEDFDM': ['thameslink'] },
	Bellingham: { '910GBELNGHM': ['thameslink'] },
	Belvedere: { '910GBELVEDR': ['thameslink'] },
	Bickley: { '910GBICKLEY': ['thameslink'] },
	Biggleswade: { '910GBIGLSWD': ['thameslink'] },
	Blackheath: { '910GBLKHTH': ['thameslink'] },
	'Brent Cross West': { '910GBRENTX': ['thameslink'] },
	Brighton: { '910GBRGHTN': ['thameslink'] },
	Barnehurst: { '910GBRNHRST': ['thameslink'] },
	'Bromley South': { '910GBROMLYS': ['thameslink'] },
	'Burgess Hill': { '910GBURGESH': ['thameslink'] },
	Bexleyheath: { '910GBXLYHTH': ['thameslink'] },
	Cambridge: { '910GCAMBDGE': ['thameslink'] },
	Catford: { '910GCATFORD': ['thameslink'] },
	'Crofton Park': { '910GCFPK': ['thameslink'] },
	Chatham: { '910GCHATHAM': ['thameslink'] },
	'Coulsdon South': { '910GCOLSDNS': ['thameslink'] },
	Crawley: { '910GCRAWLEY': ['thameslink'] },
	Cricklewood: { '910GCRKLWD': ['thameslink'] },
	Charlton: { '910GCRLN': ['thameslink'] },
	Carshalton: { '910GCRSHLTN': ['thameslink'] },
	'City Thameslink': { '910GCTMSLNK': ['thameslink'] },
	Dartford: { '910GDARTFD': ['thameslink'] },
	Deptford: { '910GDEPTFD': ['thameslink'] },
	Dormans: { '910GDORMANS': ['thameslink'] },
	Earlswood: { '910GEARLSWD': ['thameslink'] },
	'East Croydon': {
		'910GECROYDN': ['thameslink'],
		'9400ZZCRECR1': ['tram'],
		'9400ZZCRECR2': ['tram'],
		'940GZZCRECR': ['tram']
	},
	'East Grinstead': { '910GEGRNSTD': ['thameslink'] },
	Eltham: { '910GELTHAM': ['thameslink'] },
	'Elstree & Borehamwood': { '910GELTR': ['thameslink'] },
	Erith: { '910GERITH': ['thameslink'] },
	'Mitcham Eastfields': { '910GESTFLDS': ['thameslink'] },
	Eynsford: { '910GEYNSFD': ['thameslink'] },
	Faygate: { '910GFAYGATE': ['thameslink'] },
	Flitwick: { '910GFLITWCK': ['thameslink'] },
	Foxton: { '910GFOXTON': ['thameslink'] },
	Gillingham: { '910GGLNGHMK': ['thameslink'] },
	'Greenhithe for Bluewater': { '910GGNHT': ['thameslink'] },
	Gravesend: { '910GGRVSEND': ['thameslink'] },
	'Gatwick Airport': { '910GGTWK': ['thameslink'], '920GLGW0': ['thameslink'] },
	'Hadley Wood': { '910GHADLYWD': ['thameslink'] },
	Hassocks: { '910GHASOCKS': ['thameslink'] },
	Hatfield: { '910GHATFILD': ['thameslink'] },
	Hendon: { '910GHDON': ['thameslink'] },
	'Herne Hill': { '910GHERNEH': ['thameslink'] },
	Higham: { '910GHIGM': ['thameslink'] },
	Hitchin: { '910GHITCHIN': ['thameslink'] },
	Hackbridge: { '910GHKBG': ['thameslink'] },
	Huntingdon: { '910GHNTNGDN': ['thameslink'] },
	Horley: { '910GHORLEY': ['thameslink'] },
	Horsham: { '910GHORSHAM': ['thameslink'] },
	Harlington: { '910GHRLG': ['thameslink'] },
	Harpenden: { '910GHRPNDN': ['thameslink'] },
	'Hurst Green': { '910GHRSTGRN': ['thameslink'] },
	'Haydons Road': { '910GHYDNSRD': ['thameslink'] },
	'Haywards Heath': { '910GHYWRDSH': ['thameslink'] },
	Ifield: { '910GIFIELD': ['thameslink'] },
	'Kent House': { '910GKENTHOS': ['thameslink'] },
	Knebworth: { '910GKNEBWTH': ['thameslink'] },
	"King's Cross": { '910GKNGX': ['thameslink'] },
	'Loughborough Junction': { '910GLBGHJN': ['thameslink'] },
	Leagrave: { '910GLEAGRVE': ['thameslink'] },
	Littlehaven: { '910GLHVN': ['thameslink'] },
	Lingfield: { '910GLINGFLD': ['thameslink'] },
	Letchworth: { '910GLTCE': ['thameslink'] },
	'Luton Airport Parkway': { '910GLUTOAPY': ['thameslink'] },
	Luton: { '910GLUTON': ['thameslink'] },
	'Maze Hill': { '910GMAZEH': ['thameslink'] },
	Meldreth: { '910GMELDRTH': ['thameslink'] },
	Merstham: { '910GMERSTHM': ['thameslink'] },
	'Mitcham Junction': {
		'910GMITCHMJ': ['thameslink'],
		'9400ZZCRMJT1': ['tram'],
		'9400ZZCRMJT2': ['tram'],
		'940GZZCRMJT': ['tram']
	},
	'Mill Hill Broadway': { '910GMLHB': ['thameslink'] },
	'Morden South': { '910GMORDENS': ['thameslink'] },
	'New Barnet': { '910GNBARNET': ['thameslink'] },
	'New Southgate': { '910GNEWSGAT': ['thameslink'] },
	Northfleet: { '910GNRTHFLT': ['thameslink'] },
	Nunhead: { '910GNUNHEAD': ['thameslink'] },
	'Oakleigh Park': { '910GOKLGHPK': ['thameslink'] },
	Orpington: { '910GORPNGTN': ['thameslink'] },
	Otford: { '910GOTFORD': ['thameslink'] },
	Oxted: { '910GOXTED': ['thameslink'] },
	Peterborough: { '910GPBRO': ['thameslink'] },
	'Petts Wood': { '910GPETSWD': ['thameslink'] },
	Plumstead: { '910GPLMS': ['thameslink'] },
	'Penge East': { '910GPNGEE': ['thameslink'] },
	'Potters Bar': { '910GPOTRSBR': ['thameslink'] },
	'Preston Park': { '910GPRSP': ['thameslink'] },
	Purley: { '910GPURLEY': ['thameslink'] },
	Radlett: { '910GRADLETT': ['thameslink'] },
	Rainham: { '910GRAINHMK': ['thameslink'] },
	Ravensbourne: { '910GRBRN': ['thameslink'] },
	Rochester: { '910GRCHT': ['thameslink'] },
	Riddlesdown: { '910GRDLSDWN': ['thameslink'] },
	Redhill: { '910GREDHILL': ['thameslink'] },
	Royston: { '910GROYSTON': ['thameslink'] },
	Salfords: { '910GSALFDS': ['thameslink'] },
	'South Croydon': { '910GSCROYDN': ['thameslink'] },
	Sanderstead: { '910GSDSD': ['thameslink'] },
	Selhurst: { '910GSELHRST': ['thameslink'] },
	'St Helier': { '910GSHLIER': ['thameslink'] },
	Shepreth: { '910GSHPRTH': ['thameslink'] },
	Shoreham: { '910GSHRMKT': ['thameslink'] },
	Shortlands: { '910GSHRTLND': ['thameslink'] },
	'Slade Green': { '910GSLADEGN': ['thameslink'] },
	'South Merton': { '910GSMERTON': ['thameslink'] },
	Sandy: { '910GSNDY': ['thameslink'] },
	'St Albans City': { '910GSTALBCY': ['thameslink'] },
	'Stone Crossing': { '910GSTCR': ['thameslink'] },
	Stevenage: { '910GSTEVNGE': ['thameslink'] },
	'St Mary Cray': { '910GSTMRYC': ['thameslink'] },
	'St Neots': { '910GSTNEOTS': ['thameslink'] },
	'St Pancras International': { '910GSTPX': ['thameslink'] },
	'St Pancras International LL': { '910GSTPXBOX': ['thameslink'] },
	Streatham: { '910GSTRETHM': ['thameslink'] },
	Strood: { '910GSTROOD': ['thameslink'] },
	Sutton: { '910GSUTTON': ['thameslink'] },
	'Sutton Common': { '910GSUTTONC': ['thameslink'] },
	Sevenoaks: { '910GSVNOAKS': ['thameslink'] },
	Swanley: { '910GSWLY': ['thameslink'] },
	Swanscombe: { '910GSWNSCMB': ['thameslink'] },
	'Sydenham Hill': { '910GSYDNHMH': ['thameslink'] },
	'Three Bridges': { '910GTHBDGS': ['thameslink'] },
	Tooting: { '910GTOOTING': ['thameslink'] },
	'Tulse Hill': { '910GTULSEH': ['thameslink'] },
	'Upper Warlingham': { '910GUWRLNGH': ['thameslink'] },
	'Westcombe Park': { '910GWCOMBEP': ['thameslink'] },
	'West Dulwich': { '910GWDULWCH': ['thameslink'] },
	'West Hampstead Thameslink': { '910GWHMPSTM': ['thameslink'] },
	Whyteleafe: { '910GWHYTELF': ['thameslink'] },
	'Wimbledon Chase': { '910GWIMLCHS': ['thameslink'] },
	Woldingham: { '910GWLDNGHM': ['thameslink'] },
	'Welwyn Garden City': { '910GWLWYNGC': ['thameslink'] },
	'Welwyn North': { '910GWLWYNN': ['thameslink'] },
	'Woolwich Dockyard': { '910GWOLWCDY': ['thameslink'] },
	'West Sutton': { '910GWSUTTON': ['thameslink'] },
	Wivelsfield: { '910GWVLSFLD': ['thameslink'] },
	'Town Pier': { '930GGVS': ['thameslink'] },
	Addiscombe: {
		'9400ZZCRADD1': ['tram'],
		'9400ZZCRADD2': ['tram'],
		'940GZZCRADD': ['tram']
	},
	'Addington Village': {
		'9400ZZCRADV1': ['tram'],
		'9400ZZCRADV2': ['tram'],
		'940GZZCRADV': ['tram']
	},
	'Ampere Way': {
		'9400ZZCRAMP1': ['tram'],
		'9400ZZCRAMP2': ['tram'],
		'940GZZCRAMP': ['tram']
	},
	Arena: {
		'9400ZZCRARA1': ['tram'],
		'9400ZZCRARA2': ['tram'],
		'940GZZCRARA': ['tram']
	},
	'Avenue Road': {
		'9400ZZCRAVE1': ['tram'],
		'9400ZZCRAVE2': ['tram'],
		'940GZZCRAVE': ['tram']
	},
	'Beddington Lane': {
		'9400ZZCRBED1': ['tram'],
		'9400ZZCRBED2': ['tram'],
		'940GZZCRBED': ['tram']
	},
	'Belgrave Walk': {
		'9400ZZCRBGV1': ['tram'],
		'9400ZZCRBGV2': ['tram'],
		'940GZZCRBGV': ['tram']
	},
	Birkbeck: { '9400ZZCRBIR1': ['tram'], '940GZZCRBIR': ['tram'] },
	'Blackhorse Lane': {
		'9400ZZCRBLA1': ['tram'],
		'9400ZZCRBLA2': ['tram'],
		'940GZZCRBLA': ['tram']
	},
	'Beckenham Road': { '9400ZZCRBRD1': ['tram'], '940GZZCRBRD': ['tram'] },
	'George Street': { '9400ZZCRCEN1': ['tram'], '940GZZCRCEN': ['tram'] },
	'Church Street': { '9400ZZCRCHR1': ['tram'], '940GZZCRCHR': ['tram'] },
	'Coombe Lane': {
		'9400ZZCRCOO1': ['tram'],
		'9400ZZCRCOO2': ['tram'],
		'940GZZCRCOO': ['tram']
	},
	Centrale: { '9400ZZCRCTR1': ['tram'], '940GZZCRCTR': ['tram'] },
	'Dundonald Road': {
		'9400ZZCRDDR1': ['tram'],
		'9400ZZCRDDR2': ['tram'],
		'940GZZCRDDR': ['tram']
	},
	'Elmers End': { '9400ZZCRELM1': ['tram'], '940GZZCRELM': ['tram'] },
	Fieldway: {
		'9400ZZCRFLD1': ['tram'],
		'9400ZZCRFLD2': ['tram'],
		'940GZZCRFLD': ['tram']
	},
	'Gravel Hill': {
		'9400ZZCRGRA1': ['tram'],
		'9400ZZCRGRA2': ['tram'],
		'940GZZCRGRA': ['tram']
	},
	'Harrington Road': {
		'9400ZZCRHAR1': ['tram'],
		'9400ZZCRHAR2': ['tram'],
		'940GZZCRHAR': ['tram']
	},
	"King Henry's Drive": {
		'9400ZZCRKGH1': ['tram'],
		'9400ZZCRKGH2': ['tram'],
		'940GZZCRKGH': ['tram']
	},
	'Lebanon Road': {
		'9400ZZCRLEB1': ['tram'],
		'9400ZZCRLEB2': ['tram'],
		'940GZZCRLEB': ['tram']
	},
	'Lloyd Park': {
		'9400ZZCRLOY1': ['tram'],
		'9400ZZCRLOY2': ['tram'],
		'940GZZCRLOY': ['tram']
	},
	Mitcham: {
		'9400ZZCRMCH1': ['tram'],
		'9400ZZCRMCH2': ['tram'],
		'940GZZCRMCH': ['tram']
	},
	'Morden Road': {
		'9400ZZCRMDN1': ['tram'],
		'9400ZZCRMDN2': ['tram'],
		'940GZZCRMDN': ['tram']
	},
	'Merton Park': {
		'9400ZZCRMTP1': ['tram'],
		'9400ZZCRMTP2': ['tram'],
		'940GZZCRMTP': ['tram']
	},
	'New Addington': { '9400ZZCRNWA1': ['tram'], '940GZZCRNWA': ['tram'] },
	'Phipps Bridge': {
		'9400ZZCRPHI1': ['tram'],
		'9400ZZCRPHI2': ['tram'],
		'940GZZCRPHI': ['tram']
	},
	'Reeves Corner': { '9400ZZCRRVC1': ['tram'], '940GZZCRRVC': ['tram'] },
	Sandilands: {
		'9400ZZCRSAN1': ['tram'],
		'9400ZZCRSAN2': ['tram'],
		'940GZZCRSAN': ['tram']
	},
	'Therapia Lane': {
		'9400ZZCRTPA1': ['tram'],
		'9400ZZCRTPA2': ['tram'],
		'940GZZCRTPA': ['tram']
	},
	'Waddon Marsh': {
		'9400ZZCRWAD1': ['tram'],
		'9400ZZCRWAD2': ['tram'],
		'940GZZCRWAD': ['tram']
	},
	'Wandle Park': {
		'9400ZZCRWAN1': ['tram'],
		'9400ZZCRWAN2': ['tram'],
		'940GZZCRWAN': ['tram']
	},
	'Wellesley Road': { '9400ZZCRWEL1': ['tram'], '940GZZCRWEL': ['tram'] },
	Woodside: {
		'9400ZZCRWOD1': ['tram'],
		'9400ZZCRWOD2': ['tram'],
		'940GZZCRWOD': ['tram']
	}
};

export const lineNames: { [key: string]: string } = {
	dlr: 'DLR',
	elizabeth: 'Elizabeth line',
	bakerloo: 'Bakerloo',
	central: 'Central',
	circle: 'Circle',
	district: 'District',
	'hammersmith-city': 'Hammersmith & City',
	jubilee: 'Jubilee',
	metropolitan: 'Metropolitan',
	northern: 'Northern',
	piccadilly: 'Piccadilly',
	victoria: 'Victoria',
	'waterloo-city': 'Waterloo & City',
	liberty: 'Liberty',
	lioness: 'Lioness',
	mildmay: 'Mildmay',
	suffragette: 'Sufferagette',
	weaver: 'Weaver',
	windrush: 'Windrust',
	thameslink: 'Thameslink',
	tram: 'Tram'
};
